OAUTH_TOKEN = 'OAUTH KEY OF YOUR TWITCH BOT' # example oauth:123453453675857655758585
BOT_USERNAME = 'BOT USERNAME'
STREAM_CHANNEL_NAME = 'ID OF STREAMER CHANNEL'
# GOOGLE_SHEETS_FILE_NAME = 'Результаты'
GOOGLE_SHEETS_FILE_URL = 'URL OF GSHEET WE NEED'
SPREAD_SHEETS_DIRECTORY = 'client_secret.json' # secret json for gsheets api
STREAM_ALLOWED_USERS = 'ADMINS-ID' # can be multiple
TIMER_FOR_VOTING = 15
